<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.1.6
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Inicio',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => 'compartir.html',
	'email' => array(
		'from' => 'correo@elvalordeloautentico.com',
		'to' => 'correo@elvalordeloautentico.com'
	),
	'fields' => array(
		'custom_U301' => array(
			'type' => 'string',
			'label' => 'Nombre y apellidos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre y apellidos\' es obligatorio.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Código de barras Reyno Gourmet',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Código de barras Reyno Gourmet\' es obligatorio.',
				'format' => 'El campo \'Código de barras Reyno Gourmet\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U277' => array(
			'type' => 'string',
			'label' => 'Fecha del ticket de compra',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Fecha del ticket de compra\' es obligatorio.'
			)
		),
		'custom_U273' => array(
			'type' => 'string',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.'
			)
		),
		'custom_U281' => array(
			'type' => 'string',
			'label' => 'Nombra tu sueño o proyecto',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombra tu sueño o proyecto\' es obligatorio.'
			)
		),
		'custom_U269' => array(
			'type' => 'string',
			'label' => 'O elige un proyecto ya registrado',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'O elige un proyecto ya registrado\' es obligatorio.'
			)
		),
		'custom_U308' => array(
			'type' => 'checkbox',
			'label' => 'Estoy de acuerdo con los términos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Estoy de acuerdo con los términos\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
